apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.demo_cpg.name }}-config
data:
  application.properties: |
    management.endpoints.web.exposure.include=*
    management.server.port={{ .Values.demo_cpg.managementPort }}
    logging.level.org.springframework.cloud=DEBUG
    spring.neo4j.uri=bolt://neo4j:7687
    spring.neo4j.authentication.username=neo4j
    spring.neo4j.authentication.password={{ .Values.neo4j.neo4j.password }}
