apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    {{- include "common.labels" (merge (dict "service" .Values.demo) .) | nindent 4 }}
spec:
  selector:
    matchLabels:
      io.kompose.service: demo
  strategy:
    # Because of shared volume with multi-attach problem
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "pod.common.labels" (merge (dict "service" .Values.demo ) .) | nindent 8 }}
      annotations:
        {{- include "pod.common.annotations" (dict "service" .Values.demo ) | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: demo
          {{- include "spring-boot.common" (merge (dict "service" .Values.demo) .) | nindent 10 }}
          env:
            {{- include "spring-boot.common.env" (merge (dict "service" .Values.demo) .) | nindent 12 }}
            - name: JAVA_TOOL_OPTIONS
              value: -XX:ReservedCodeCacheSize=48M
          volumeMounts:
            - {{ include "spring-boot.config-volume-mount" . | indent 14 | trim }}
              - name: fs-storage
                mountPath: /home/cnb/files
          {{- include "spring-boot.management" .Values.demo | nindent 10 }}
          resources:
            limits:
              memory: 500M
            requests:
              memory: 300M
      volumes:
        - {{ include "spring-boot.config-volume" (dict "service" .Values.demo) | indent 10 | trim }}
        - name: fs-storage
          persistentVolumeClaim:
            claimName: {{ .Values.demo.name }}-fs-storage
