apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    {{- include "common.labels" (merge (dict "service" .Values.gateway) .) | nindent 4 }}
spec:
  selector:
    matchLabels:
      io.kompose.service: gateway
  template:
    metadata:
      labels:
        io.kompose.service: gateway
    spec:
      restartPolicy: Always
      {{- include "spring-boot.securityContext" . | nindent 6 }}
      containers:
        - name: gateway
          {{- include "spring-boot.common" (merge (dict "service" .Values.gateway) .) | nindent 10 }}
          env:
            {{- include "spring-boot.common.env" (merge (dict "service" .Values.orchestrator) .) | nindent 12 }}
          {{- include "spring-boot.management" .Values.gateway | nindent 10 }}
          volumeMounts:
            - {{ include "spring-boot.config-volume-mount" . | indent 14 | trim }}
      volumes:
        - {{ include "spring-boot.config-volume" (dict "service" .Values.gateway) | indent 10 | trim }}
