apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.gateway.name }}-config
data:
  application.properties: |
    gateway.backend.url=http://backend
    gateway.frontend.url=http://frontend
    gateway.sandbox.url=http://sandbox
    gateway.demo-cpg.url=http://demo-cpg
    gateway.demo.url=http://demo
    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
    management.server.port={{ .Values.gateway.managementPort }}
    {{ if .Values.gateway.applicationProperties }}
    {{- .Values.gateway.applicationProperties | nindent 4 }}
    {{ end }}
