{{- if not .Values.mysql.external -}}

  {{- if eq .Values.profile "dev" -}}
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
stringData:
  spring.datasource.backend-url: 'jdbc:mysql://mysql-service:3306/{{ .Values.mysql.backend_schema }}'
  spring.datasource.demo-url: 'jdbc:mysql://mysql-service:3306/{{ .Values.mysql.demo_schema }}'
  spring.datasource.username: root
  spring.datasource.password: {{ .Values.mysql.root_password | quote }}

---
  {{ end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  annotations:
    io.kompose.service: mysql
spec:
  selector:
    matchLabels:
      io.kompose.service: mysql
  template:
    metadata:
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - image: mysql:8.0.28-oracle
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.root_password | quote }}
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: /home/data/mysql
{{- end }}
