apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.orchestrator.name }}-config
data:
  application.properties: |
    orchestrator.backend-url=http://backend/internal

    orchestrator.kubernetes.apiServerUrl=http://kubernetes.default.svc
    orchestrator.kubernetes.serviceAccount=${POD_SERVICE_ACCOUNT}
    orchestrator.kubernetes.namespace=${POD_NAMESPACE}

    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
    management.server.port={{ .Values.orchestrator.managementPort }}
    orchestrator.agent-settings.heartbeat-url=http://{{ .Values.orchestrator.name }}/heartbeat
    orchestrator.agent-settings.debug=true

    logging.level.com.saveourtool.save.orchestrator.kubernetes=DEBUG
    logging.level.org.springframework=DEBUG

    {{ if .Values.orchestrator.applicationProperties }}
    {{- .Values.orchestrator.applicationProperties | nindent 4 }}
    {{ end }}