apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  labels:
    {{- include "common.labels" (merge (dict "service" .Values.orchestrator) .) | nindent 4 }}
spec:
  selector:
    matchLabels:
      io.kompose.service: orchestrator
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "pod.common.labels" (merge (dict "service" .Values.orchestrator ) .) | nindent 8 }}
      annotations:
        {{- include "pod.common.annotations" (dict "service" .Values.backend ) | nindent 8 }}
    spec:
      serviceAccountName: orchestrator-sa
      restartPolicy: Always
      {{- if .Values.orchestrator.nodeName }}
      nodeName: {{ .Values.orchestrator.nodeName }}
      {{- end }}
      {{- include "cnb.securityContext" . | nindent 6 }}
      containers:
        - name: orchestrator
          {{- include "spring-boot.common" (merge (dict "service" .Values.orchestrator) .) | nindent 10 }}
          env:
            {{- include "spring-boot.common.env" (merge (dict "service" .Values.orchestrator) .) | nindent 12 }}
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAVA_TOOL_OPTIONS
              value: -XX:ReservedCodeCacheSize=48M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - {{ include "spring-boot.config-volume-mount" . | indent 14 | trim }}
          {{- include "spring-boot.management" .Values.orchestrator | nindent 10 }}
          resources:
            limits:
              memory: 800M
            requests:
              memory: 600M
      volumes:
        - {{ include "spring-boot.config-volume" (dict "service" .Values.orchestrator) | indent 10 | trim }}
