apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.sandbox.name }}-config
data:
  application.properties: |
    orchestrator.kubernetes.apiServerUrl=http://kubernetes.default.svc
    orchestrator.kubernetes.serviceAccount=${POD_SERVICE_ACCOUNT}
    orchestrator.kubernetes.namespace=${POD_NAMESPACE}

    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
    management.server.port={{ .Values.sandbox.managementPort }}
    spring.datasource.url=${spring.datasource.sandbox-url}

    sandbox.agent-settings.sandbox-url=http://{{ .Values.sandbox.name }}
    orchestrator.agent-settings.heartbeat-url=http://{{ .Values.sandbox.name }}/heartbeat
    orchestrator.agent-settings.debug=true

    logging.level.com.saveourtool.save.orchestrator.kubernetes=DEBUG

    {{ if .Values.sandbox.applicationProperties }}
    {{- .Values.sandbox.applicationProperties | nindent 4 }}
    {{ end }}